# Configuration for Salesforce Org Analyzer
analysis:
  parser:
    include_inner_classes: true
    parse_annotations: true
    track_dml: true
    track_soql: true
    parse_doc_comments: true

execution:
  max_depth: 10
  include_workflow: true
  include_process_builder: true
  include_flows: true
  follow_apex: true
  max_iterations: 100
  track_sharing: true

visualization:
  diagram_type: mermaid
  include_conditions: true
  show_dml_operations: true
  show_soql_queries: true
  show_order: true
  style:
    trigger: "#f96"
    flow: "#9cf"
    process_builder: "#9f9"
    workflow: "#f9f"
    apex: "#ff9"

llm:
  model: "codellama/CodeLlama-7b-hf"
  temperature: 0.1
  max_length: 2048
  prompt_template: |
    Analyze the following Salesforce automation and provide documentation:

    {input}

    Focus on:
    1. Purpose and functionality
    2. Business impact
    3. Technical considerations
    4. Potential risks

logging:
  level: INFO
  file: logs/analyzer.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

output:
  format: markdown
  include_diagrams: true
  diagram_format: mermaid
  output_dir: documentation

metadata:
  types:
    - ApexClass
    - ApexTrigger
    - Flow
    - WorkflowRule
    - ValidationRule
    - CustomObject
  max_batch_size: 50
  timeout: 300
  retry_count: 3